version: '3.3'
services:
  hello:
    image: rancher/hello-world:latest
    networks:
      - webproxy
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.1'
          memory: 8M
        limits:
          cpus: '0.4'
          memory: 64M
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.${APPNAME}.entrypoints=websecure
        - traefik.http.routers.${APPNAME}.rule=Host(`${APPNAME}.xops.ipv9.me`)
        - traefik.http.routers.${APPNAME}.tls.certresolver=default
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=80

networks:
  webproxy:
    external: true
