version: '3.3'
services:
  hello:
    image: rancher/hello-world:latest
#    ports:
#      - 80
    networks:
      - webproxy
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.1'
          memory: 8M
        limits:
          cpus: '0.4'
          memory: 64M
      labels:
        traefik.docker.network: webproxy
        traefik.enable: 'true'
        traefik.http.routers.hello100-https.entrypoints: websecure
        traefik.http.routers.hello100-https.rule: Host(`hello100.xops.ipv9.xyz`)
        traefik.http.routers.hello100-https.tls.certresolver: default
        traefik.http.services.hello100.loadbalancer.server.port: '80'

networks:
  webproxy:
    external: true
